# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'StonlyReactNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StonlyReactNative
  pod 'Stonly', '0.1.17'

end
